### ISSUE TITLE
possible bug in example code

### ISSUE THREAD

**Issue by conradsnicta** [rcurtin/ensmallen_jmlr#1]
Within the text, X is defined as having a size of (n x d), as specified here:

https://github.com/rcurtin/ensmallen_jmlr/blob/bbee2c654781940c17237d7a2089fd95f056952f/paper.tex#L380-L383

There is a possible issue in the definition of `phi_star` in the example code shown in Figure 1:
https://github.com/rcurtin/ensmallen_jmlr/blob/bbee2c654781940c17237d7a2089fd95f056952f/paper.tex#L347-L350

For the matrix multiplication in `Evaluate()` to be valid:
https://github.com/rcurtin/ensmallen_jmlr/blob/bbee2c654781940c17237d7a2089fd95f056952f/paper.tex#L336-L337

... seems that `X.n_cols` be used instead of `X.n_rows` in the definition of `phi_star`:

    arma::mat phi_star(X.n_cols, 1, arma::fill::randu);  // initial point (uniform random)

**Comment by rcurtin** [comment]
Ahhh, I'm not sure what the best solution here is.  Armadillo is column-major, so for applications like this it's generally best to store data such that an individual data point corresponds to a column.  So, the implementation does that, and that's good.  But, the definition in the paper of the predictors is row-major---which is more in line with papers and textbooks.

It seems like the best approach would be simply to change the definition of the predictors in the paper to `\mathcal{R}^{d \times n}`, even though this is somewhat at odds with what readers will expect.  Maybe there's extra space in there to even point out why we chose a column-major representation, but if not, maybe it doesn't hurt to omit that extra detail.

If we changed the paper to use a row-major implementation in ensmallen, this might be confusing to users, who either end up writing inefficient code, or encounter other code that uses ensmallen differently.  So to me it seems like there are more disadvantages to changing the code than changing the definition, but I'm not certain.

What do you think?  I'm happy to make the change, but I want to make sure I'm not overlooking any better ideas or anything. :)

**Comment by conradsnicta** [comment]
Let's keep it column major, as that's the most efficient representation (and as $DEITY intended).
I presume this means X will have a size of (d x n).

Perhaps a straightforward change to the maths in the paper is to simply use X^T instead of X.

PS. I really don't know why people use row-major.  The mathematical definition of a vector is by default a column vector. On top of that, LAPACK (and hence Matlab and Octave) has used column major storage since the dinosaurs roamed the earth :)  People sometimes use the excuse that the C language uses row-major, but that's just bonkers as C has no definition of a matrix.  C is neither row-major nor column-major.

**Comment by conradsnicta** [comment]
> ... change the definition of the predictors in the paper to \mathcal{R}^{d \times n}, even though this is somewhat at odds with what readers will expect. Maybe there's extra space in there to even point out why we chose a column-major representation, but if not, maybe it doesn't hurt to omit that extra detail.

Perhaps omit it for now.  If a reviewer asks a question on this, we can explain in the rebuttal. If necessary, we can sacrifice a line somewhere to simply state that we're using column-major ordering to ensure efficiency with Armadillo and LAPACK (or something along these lines).

**Comment by rcurtin** [comment]
:+1: Let me know what you think of #3; if you're good with it, then we can go with that and I can update the technical report on arXiv also.

**Comment by conradsnicta** [comment]
#3 appears incomplete, ie. the matrix multiplications don't have conforming sizes.
I've created #4 which adjusts the maths via transposes, in both the text and code.

**Comment by rcurtin** [comment]
Thanks, you're right---#4 is merged now, so this is fixed.
